set_property PACKAGE_PIN R14 [get_ports {led[0]}]
set_property PACKAGE_PIN P14 [get_ports {led[1]}]
set_property PACKAGE_PIN N16 [get_ports {led[2]}]
set_property PACKAGE_PIN M14 [get_ports {led[3]}]
set_property PACKAGE_PIN M20 [get_ports {sw[1]}]
set_property PACKAGE_PIN M19 [get_ports {sw[0]}]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN L19 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
create_clock -period 8.000 -name clk -waveform {0.000 4.000} [get_ports -filter { NAME =~  "*clk*" && DIRECTION == "IN" }]
create_generated_clock -name clk_div -source [get_ports clk] -devide_by 125000000 [get_pins div_0/clk_div_reg/Q]
